[package]
name = "parser"
version = "0.0.1"
edition = "2021"

[build-dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"

[dependencies]
cfgrammar = "0.13"
lrlex = "0.13"
lrpar = "0.13"
arbitrary = { version = "1", features = ["derive"] }
